# Generated by Django 4.0.1 on 2022-02-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_admin_author_news_remove_book_publisheddata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('Undefined', 'Undefined'), ('Completed', 'Completed'), ('Knowledge', 'Knowledge'), ('Good', 'Good'), ('Bad', 'Bad')], default='Undefined', max_length=50),
        ),
    ]
