# Generated by Django 4.0.1 on 2022-02-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_news_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.TextField()),
                ('role', models.CharField(choices=[('Undefined', 'Undefined'), ('Admin', 'Admin'), ('Moderator', 'Moderator'), ('Editor', 'Editor'), ('Analyst', 'Analyst')], default='Undefined', max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('online', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Undefined', 'Undefined'), ('Adventure', 'Adventure'), ('Biography', 'Biography'), ('Dystopia', 'Dystopia'), ('Fantastic', 'Fantastic'), ('Horror', 'Horror'), ('Science', 'Science'), ('ScienceFiction', 'Science Fiction'), ('Poetry', 'Poetry')], default='Undefined', max_length=50),
        ),
    ]
